// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rqkpqrkiufdcwxzruxjg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxa3BxcmtpdWZkY3d4enJ1eGpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMTkyMjQsImV4cCI6MjA3MTg5NTIyNH0.nYTqYI9dFQwLOjmYmLH7ejIuSZeJEvE7lm8l6ReOxEU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});